import type { AdminBusiness } from "../model/business.type";

// Sample data: replaced by real businesses once the database exists.
export const ADMIN_BUSINESSES: AdminBusiness[] = [
  {
    id: "b1",
    name: "Restaurant name",
    slug: "restaurant",
    ownerName: "Pema Wangmo",
    ownerEmail: "pema@example.com",
    category: "Food",
    dzongkhag: "Thimphu",
    status: "VERIFIED",
    promotions: 6,
    followers: 412,
    joined: "2026-06-14",
  },
  {
    id: "b2",
    name: "Textile house",
    slug: "textile-house",
    ownerName: "Karma Dorji",
    ownerEmail: "karma@example.com",
    category: "Fashion",
    dzongkhag: "Thimphu",
    status: "VERIFIED",
    promotions: 9,
    followers: 688,
    joined: "2026-05-02",
  },
  {
    id: "b3",
    name: "Café name",
    slug: "cafe",
    ownerName: "Sonam Choden",
    ownerEmail: "sonam@example.com",
    category: "Cafés",
    dzongkhag: "Thimphu",
    status: "VERIFIED",
    promotions: 4,
    followers: 255,
    joined: "2026-07-21",
  },
  {
    id: "b4",
    name: "Spa name",
    slug: "spa-name",
    ownerName: "Tshering Lhamo",
    ownerEmail: "tshering@example.com",
    category: "Wellness",
    dzongkhag: "Thimphu",
    status: "VERIFIED",
    promotions: 3,
    followers: 190,
    joined: "2026-08-03",
  },
  {
    id: "b5",
    name: "Gym name",
    slug: "gym",
    ownerName: "Dechen Zangmo",
    ownerEmail: "dechen@example.com",
    category: "Wellness",
    dzongkhag: "Paro",
    status: "PENDING",
    promotions: 0,
    followers: 0,
    joined: "2026-10-05",
  },
  {
    id: "b6",
    name: "Boutique name",
    slug: "boutique",
    ownerName: "Ugyen Tenzin",
    ownerEmail: "ugyen@example.com",
    category: "Fashion",
    dzongkhag: "Paro",
    status: "PENDING",
    promotions: 1,
    followers: 0,
    joined: "2026-10-04",
  },
  {
    id: "b7",
    name: "Bakery name",
    slug: "bakery",
    ownerName: "Yeshey Dema",
    ownerEmail: "yeshey@example.com",
    category: "Food",
    dzongkhag: "Punakha",
    status: "VERIFIED",
    promotions: 5,
    followers: 321,
    joined: "2026-04-18",
  },
  {
    id: "b8",
    name: "Homestay name",
    slug: "homestay",
    ownerName: "Jigme Norbu",
    ownerEmail: "jigme@example.com",
    category: "Stays",
    dzongkhag: "Bumthang",
    status: "VERIFIED",
    promotions: 2,
    followers: 143,
    joined: "2026-08-29",
  },
  {
    id: "b9",
    name: "Tea house name",
    slug: "tea-house-name",
    ownerName: "Kinley Pelden",
    ownerEmail: "kinley@example.com",
    category: "Cafés",
    dzongkhag: "Thimphu",
    status: "PENDING",
    promotions: 0,
    followers: 0,
    joined: "2026-10-06",
  },
  {
    id: "b10",
    name: "Phone repair name",
    slug: "phone-repair-name",
    ownerName: "Namgay Tshomo",
    ownerEmail: "namgay@example.com",
    category: "Electronics",
    dzongkhag: "Chhukha",
    status: "SUSPENDED",
    promotions: 2,
    followers: 76,
    joined: "2026-03-09",
  },
  {
    id: "b11",
    name: "Bookshop name",
    slug: "bookshop-name",
    ownerName: "Rinchen Dolma",
    ownerEmail: "rinchen@example.com",
    category: "Books",
    dzongkhag: "Thimphu",
    status: "VERIFIED",
    promotions: 3,
    followers: 98,
    joined: "2026-09-12",
  },
  {
    id: "b12",
    name: "Guesthouse name",
    slug: "guesthouse-name",
    ownerName: "Lhaki Wangchuk",
    ownerEmail: "lhaki@example.com",
    category: "Stays",
    dzongkhag: "Paro",
    status: "PENDING",
    promotions: 0,
    followers: 0,
    joined: "2026-10-07",
  },
];
