import type { Report } from "../model/report.type";

// Sample data: replaced by real reports once the database exists.
export const REPORTS: Report[] = [
  {
    id: "r1",
    promotionTitle: "20% off hand-woven kira",
    promotionSlug: "kira",
    businessName: "Textile house",
    reason: "MISLEADING",
    details: "The sale ended last week but the page still shows 20% off.",
    count: 3,
    firstReported: "2026-10-06T15:20",
    status: "OPEN",
  },
  {
    id: "r2",
    promotionTitle: "Phone trade-in offer",
    promotionSlug: "trade-in",
    businessName: "[Mobile shop]",
    reason: "WRONG_PRICE",
    details: "In store the discount was 5%, not 15%.",
    count: 2,
    firstReported: "2026-10-06T11:05",
    status: "OPEN",
  },
  {
    id: "r3",
    promotionTitle: "Free massage oil with hot stone bath",
    promotionSlug: "hot-stone",
    businessName: "Spa name",
    reason: "SPAM",
    details: "Posted the same offer many times.",
    count: 5,
    firstReported: "2026-10-05T18:45",
    status: "OPEN",
  },
  {
    id: "r4",
    promotionTitle: "Second pizza free on Fridays",
    promotionSlug: "pizza-fridays",
    businessName: "[Pizzeria]",
    reason: "CLOSED",
    details: "The restaurant has closed down.",
    count: 1,
    firstReported: "2026-10-04T09:30",
    status: "OPEN",
  },
  {
    id: "r5",
    promotionTitle: "Winter coats clearance",
    promotionSlug: "winter-coats-clearance",
    businessName: "Boutique name",
    reason: "OFFENSIVE",
    details: "The photo used is not appropriate.",
    count: 1,
    firstReported: "2026-10-03T14:10",
    status: "RESOLVED",
    decision: "REMOVED",
  },
  {
    id: "r6",
    promotionTitle: "Hiking boots & jackets",
    promotionSlug: "hiking",
    businessName: "[Sports store]",
    reason: "MISLEADING",
    details: "Offer says 30% off but only on one item.",
    count: 2,
    firstReported: "2026-10-02T10:00",
    status: "RESOLVED",
    decision: "WARNED",
  },
  {
    id: "r7",
    promotionTitle: "Lunch set, two for one",
    promotionSlug: "lunch-set-two-for-one",
    businessName: "Noodle bar name",
    reason: "WRONG_PRICE",
    details: "Price on the page is different in the menu.",
    count: 1,
    firstReported: "2026-09-30T12:15",
    status: "RESOLVED",
    decision: "DISMISSED",
  },
];
