import type { TaggedPromotion } from "@/components/public/model/promotion.type";

export const NEW_PLACES: TaggedPromotion[] = [
  {
    id: "n1",
    badge: "New",
    title: "[Restaurant name]",
    meta: ["Restaurant · Norzin Lam", "Opened this week"],
    highlight: "Opening-week menu",
    href: "/businesses/restaurant-name",
    tags: ["week", "food"],
  },
  {
    id: "n2",
    badge: "New",
    title: "[Café name]",
    meta: ["Café · Changzamtog", "Opened 2 weeks ago"],
    highlight: "Free tasting",
    href: "/businesses/café-name",
    tags: ["month", "cafe"],
  },
  {
    id: "n3",
    badge: "New",
    title: "[Boutique name]",
    meta: ["Clothing · Town centre", "Opened this month"],
    highlight: "New arrivals",
    href: "/businesses/boutique-name",
    tags: ["month", "shops"],
  },
  {
    id: "n4",
    badge: "New",
    title: "[Gym name]",
    meta: ["Fitness · Babesa", "Opened this month"],
    highlight: "First week free",
    href: "/businesses/gym-name",
    tags: ["month", "wellness"],
  },
  {
    id: "n5",
    badge: "New",
    title: "[Bakery name]",
    meta: ["Bakery · Chubachu", "Opened this month"],
    highlight: "Fresh daily",
    href: "/businesses/bakery-name",
    tags: ["month", "food"],
  },
  {
    id: "n6",
    badge: "New",
    title: "[Homestay name]",
    meta: ["Stay · Motithang", "Opened this month"],
    highlight: "Now open",
    href: "/businesses/homestay-name",
    tags: ["month", "stays"],
  },
  {
    id: "n7",
    badge: "New",
    title: "[Spa name]",
    meta: ["Wellness · Babesa", "Opened this week"],
    highlight: "Launch offer",
    href: "/businesses/spa-name",
    tags: ["week", "wellness"],
  },
  {
    id: "n8",
    badge: "New",
    title: "[Bookshop name]",
    meta: ["Books · Clock Tower", "Opened this week"],
    highlight: "Author signing",
    href: "/businesses/bookshop-name",
    tags: ["week", "shops"],
  },
  {
    id: "n9",
    badge: "New",
    title: "[Tea house name]",
    meta: ["Café · Olakha", "Opened this week"],
    highlight: "Free first cup",
    href: "/businesses/tea-house-name",
    tags: ["week", "cafe"],
  },
  {
    id: "n10",
    badge: "New",
    title: "[Guesthouse name]",
    meta: ["Stay · Paro town", "Opened this month"],
    highlight: "Intro rate",
    href: "/businesses/guesthouse-name",
    tags: ["month", "stays"],
  },
  {
    id: "n11",
    badge: "New",
    title: "[Noodle bar name]",
    meta: ["Restaurant · Motithang", "Opened 2 weeks ago"],
    highlight: "Lunch deal",
    href: "/businesses/noodle-bar-name",
    tags: ["month", "food"],
  },
  {
    id: "n12",
    badge: "New",
    title: "[Phone repair name]",
    meta: ["Shop · Town centre", "Opened this month"],
    highlight: "Free screen check",
    href: "/businesses/phone-repair-name",
    tags: ["month", "shops"],
  },
];
