import type { EmailCampaignItem } from "../model/email-campaign.type";

const base = {
  previewText: "",
  locations: [] as string[],
  interests: [] as string[],
  birthdayThisMonth: false,
  unsubscribed: 0,
};

// Sample data: replaced by the business's real campaigns once the database exists.
export const EMAIL_CAMPAIGNS: EmailCampaignItem[] = [
  {
    ...base,
    id: "e1",
    name: "Tshechu kira offer",
    subject: "20% off hand-woven kira this Tshechu",
    previewText: "Dress up for the festival",
    body: "Hello!\n\nFor Tshechu we're taking 20% off all hand-woven kira, in store until 20 October.\n\nCome and see the new patterns.",
    promotionId: "p1",
    status: "SENT",
    sendAt: "2026-10-06T10:00",
    recipients: 178,
    opened: 94,
    clicked: 31,
    unsubscribed: 1,
    interests: ["Fashion"],
  },
  {
    ...base,
    id: "e2",
    name: "Opening week menu",
    subject: "Our opening-week set menu is here",
    body: "We've just opened on Norzin Lam and we'd love you to try our opening-week set menu.",
    promotionId: "p2",
    status: "SENT",
    sendAt: "2026-10-01T09:30",
    recipients: 164,
    opened: 88,
    clicked: 42,
    locations: ["Thimphu"],
  },
  {
    ...base,
    id: "e3",
    name: "Winter coats preview",
    subject: "Winter coats: first look",
    body: "Our winter range lands on 12 October with up to 40% off. Here's an early look.",
    promotionId: "p5",
    status: "SCHEDULED",
    sendAt: "2026-10-12T09:00",
    recipients: 178,
    opened: 0,
    clicked: 0,
  },
  {
    ...base,
    id: "e4",
    name: "Weekend market reminder",
    subject: "",
    body: "",
    promotionId: "p3",
    status: "DRAFT",
    sendAt: "",
    recipients: 0,
    opened: 0,
    clicked: 0,
    birthdayThisMonth: false,
  },
  {
    ...base,
    id: "e5",
    name: "Giveaway teaser",
    subject: "Something is coming…",
    body: "Keep an eye out this Losar.",
    promotionId: "",
    status: "CANCELLED",
    sendAt: "2026-02-05T09:00",
    recipients: 0,
    opened: 0,
    clicked: 0,
  },
  {
    ...base,
    id: "e6",
    name: "Weekend market recap",
    subject: "Thank you for coming to the night market",
    body: "Thank you to everyone who came by our stall. Here's what's new this week.",
    promotionId: "",
    status: "SENT",
    sendAt: "2026-09-20T10:00",
    recipients: 150,
    opened: 71,
    clicked: 19,
    unsubscribed: 2,
  },
  {
    ...base,
    id: "e7",
    name: "Autumn menu launch",
    subject: "Our autumn menu is here",
    body: "We've changed the menu for the season. Come and taste what's new.",
    promotionId: "",
    status: "SENT",
    sendAt: "2026-09-12T09:30",
    recipients: 138,
    opened: 79,
    clicked: 27,
    unsubscribed: 1,
    interests: ["Food"],
  },
  {
    ...base,
    id: "e8",
    name: "Welcome to our followers",
    subject: "Thanks for following us",
    body: "We're glad you're here. Expect the occasional offer and news from us.",
    promotionId: "",
    status: "SENT",
    sendAt: "2026-09-03T11:00",
    recipients: 112,
    opened: 66,
    clicked: 22,
    unsubscribed: 0,
  },
];

export const findEmailCampaign = (id: string) =>
  EMAIL_CAMPAIGNS.find((c) => c.id === id);
