import type { TaggedPromotion } from "@/components/public/model/promotion.type";

export const DEALS: TaggedPromotion[] = [
  {
    id: "d1",
    badge: "Popular",
    title: "Second pizza free on Fridays",
    meta: ["[Pizzeria] · Motithang", "Every Friday evening"],
    highlight: "Buy 1 get 1",
    href: "/promotions/second-pizza-free-on-fridays",
    tags: ["week", "bogo", "food"],
  },
  {
    id: "d2",
    title: "Hand-woven kira for Tshechu",
    meta: ["[Textile house] · Norzin Lam", "Until 20 Oct"],
    highlight: "20% off",
    href: "/promotions/hand-woven-kira-for-tshechu",
    tags: ["week", "percent", "fashion"],
  },
  {
    id: "d3",
    title: "Phone trade-in offer",
    meta: ["[Mobile shop] · Town centre", "Until 15 Oct"],
    highlight: "15% off",
    href: "/promotions/phone-trade-in-offer",
    tags: ["week", "percent", "electronics"],
  },
  {
    id: "d4",
    badge: "Popular",
    title: "Hot stone bath package",
    meta: ["[Spa name] · Babesa", "Until 20 Oct"],
    highlight: "Free massage oil",
    href: "/promotions/hot-stone-bath-package",
    tags: ["week", "wellness"],
  },
  {
    id: "d5",
    badge: "Ends today",
    title: "Fresh bread after 7 pm",
    meta: ["[Bakery name] · Chubachu", "Every day"],
    highlight: "Half price",
    href: "/promotions/fresh-bread-after-7-pm",
    tags: ["today", "food"],
  },
  {
    id: "d6",
    title: "Hiking boots & jackets",
    meta: ["[Sports store] · Olakha", "Until 12 Oct"],
    highlight: "30% off",
    href: "/promotions/hiking-boots-jackets",
    tags: ["week", "percent", "fashion"],
  },
  {
    id: "d7",
    badge: "Ends today",
    title: "Lunch set, two for one",
    meta: ["[Restaurant] · Changzamtog", "Today only"],
    highlight: "Buy 1 get 1",
    href: "/promotions/lunch-set-two-for-one",
    tags: ["today", "bogo", "food"],
  },
  {
    id: "d8",
    title: "Wireless earbuds sale",
    meta: ["[Electronics] · Town centre", "Until 18 Oct"],
    highlight: "25% off",
    href: "/promotions/wireless-earbuds-sale",
    tags: ["week", "percent", "electronics"],
  },
  {
    id: "d9",
    title: "Yoga class pass",
    meta: ["[Studio] · Babesa", "Until 31 Oct"],
    highlight: "First class free",
    href: "/promotions/yoga-class-pass",
    tags: ["wellness"],
  },
  {
    id: "d10",
    title: "Winter coats clearance",
    meta: ["[Boutique] · Norzin Lam", "Until 25 Oct"],
    highlight: "40% off",
    href: "/promotions/winter-coats-clearance",
    tags: ["percent", "fashion"],
  },
  {
    id: "d11",
    badge: "Ends today",
    title: "Coffee & cake combo",
    meta: ["[Café] · Changzamtog", "Today only"],
    highlight: "Nu. [PRICE]",
    href: "/promotions/coffee-cake-combo",
    tags: ["today", "food"],
  },
  {
    id: "d12",
    title: "Laptop service check",
    meta: ["[Repair shop] · Chubachu", "Until 22 Oct"],
    highlight: "Free diagnosis",
    href: "/promotions/laptop-service-check",
    tags: ["week", "electronics"],
  },
];
