import type { TaggedPromotion } from "@/components/public/model/promotion.type";

export const EVENTS: TaggedPromotion[] = [
  {
    id: "e1",
    badge: "This weekend",
    title: "Festival night market",
    meta: ["[Venue] · Thimphu", "Sat 10 Oct · 5 pm"],
    highlight: "Free entry",
    href: "/events/night-market",
    tags: ["food", "weekend", "free"],
  },
  {
    id: "e2",
    title: "Live music evening",
    meta: ["[Venue] · Thimphu", "Mon 12 Oct · 7 pm"],
    highlight: "Nu. [PRICE]",
    href: "/events/live-music",
    tags: ["music"],
  },
  {
    id: "e3",
    title: "Archery open day",
    meta: ["[Venue] · Thimphu", "Sun 18 Oct · 9 am"],
    highlight: "Free entry",
    href: "/events/archery",
    tags: ["sports", "weekend", "free"],
  },
  {
    id: "e4",
    title: "Crafts fair",
    meta: ["[Venue] · Thimphu", "Sun 25 Oct · All day"],
    highlight: "Free entry",
    href: "/events/crafts-fair",
    tags: ["culture", "weekend", "free"],
  },
  {
    id: "e5",
    title: "Kids' painting workshop",
    meta: ["[Venue] · Thimphu", "Sat 31 Oct · 10 am"],
    highlight: "Nu. [PRICE]",
    href: "/events/painting",
    tags: ["kids", "weekend"],
  },
  {
    id: "e6",
    title: "Food festival",
    meta: ["[Venue] · Thimphu", "Sun 1 Nov · 11 am"],
    highlight: "Free entry",
    href: "/events/food-festival",
    tags: ["food", "weekend", "free"],
  },
  {
    id: "e7",
    title: "Traditional dance showcase",
    meta: ["[Venue] · Paro", "Fri 6 Nov · 6 pm"],
    highlight: "Nu. [PRICE]",
    href: "/events/dance",
    tags: ["culture"],
  },
  {
    id: "e8",
    title: "Acoustic open mic",
    meta: ["[Café] · Changzamtog", "Thu 12 Nov · 7 pm"],
    highlight: "Free entry",
    href: "/events/open-mic",
    tags: ["music", "free"],
  },
  {
    id: "e9",
    title: "Family football day",
    meta: ["[Ground] · Thimphu", "Sat 14 Nov · 10 am"],
    highlight: "Free entry",
    href: "/events/football",
    tags: ["sports", "weekend", "free"],
  },
  {
    id: "e10",
    title: "Story time for kids",
    meta: ["[Library] · Thimphu", "Sun 15 Nov · 11 am"],
    highlight: "Free entry",
    href: "/events/story-time",
    tags: ["kids", "weekend", "free"],
  },
  {
    id: "e11",
    title: "Wine & cheese evening",
    meta: ["[Restaurant] · Punakha", "Fri 20 Nov · 7 pm"],
    highlight: "Nu. [PRICE]",
    href: "/events/wine-cheese",
    tags: ["food"],
  },
  {
    id: "e12",
    title: "Thangka painting class",
    meta: ["[Studio] · Thimphu", "Sat 21 Nov · 2 pm"],
    highlight: "Nu. [PRICE]",
    href: "/events/thangka",
    tags: ["culture", "weekend"],
  },
];
